source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
#inhibit_all_warnings!

def common
    pod 'WeexSDK', '0.10.0'
    pod 'SDWebImage', '3.7.5'
    pod 'SocketRocket', '0.4.2'
end

target 'App' do
    common
end

target 'AppUITests' do
    common
end
